name: Setup Android SDK
description: Sets up the Android SDK and ANDROID_HOME env variable

inputs:
  commandlinetools-version:
    description: 'See: https://developer.android.com/studio#command-line-tools-only'
    required: false
    default: '11076708'

runs:
  using: composite
  steps:
    - name: Download commandline tools
      env:
        TOOLS_VERSION: ${{ inputs.commandlinetools-version }}
      run: |
        echo "Start downloading..."
        
        mkdir -p $HOME/android-sdk && cd $_
        wget https://dl.google.com/android/repository/commandlinetools-linux-${TOOLS_VERSION}_latest.zip
        unzip commandlinetools-linux-${TOOLS_VERSION}_latest.zip
        mkdir tools
        cd cmdline-tools/
        mv * ../tools && mv ../tools .
        cd ..
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        
        echo "Using Android SDK home: $ANDROID_HOME"
      shell: bash

    - name: Accept SDK licenses
      run: |
        # For some reason, sdkmanager returns an error code when licenses are accepted.
        # Run in a sub-shell so that the CI workflow doesn't fail.
        echo $(yes | $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager --licenses)
      shell: bash

    - name: Install platform tools
      run: |
        $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager --install "platform-tools"
      shell: bash
