name: Setup Android Environment
description: Sets up java, gradle and android sdk

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Setup Android SDK
      uses: ./.github/actions/setup-android-sdk

    - uses: gradle/actions/setup-gradle@v6
      id: setup-gradle
      with:
        cache-provider: basic
        cache-read-only: false

    - name: Make gradlew executable
      run: chmod +x gradlew
      shell: bash
