name: Setup Android Environment
description: Sets up java, gradle and android sdk

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Make ANDROID_HOME available to github env vars
      run: echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
      shell: bash

    - name: Setup Android SDK
      if: ${{ !env.ANDROID_HOME }}
      uses: ./.github/actions/setup-android-sdk

    - name: Setup gradle cache
      uses: gradle/actions/setup-gradle@v6
      id: setup-gradle
      with:
        cache-provider: basic
        cache-read-only: false

    - name: Make gradlew executable
      run: chmod +x gradlew
      shell: bash
