name: Android version bump
description: Overrides versionCode and versionname in build.gradle

inputs:
  bump-type:
    description: type of release bump
    required: true

runs:
  using: composite
  steps:
    - name: Bump version
      run: |
        GRADLE_FILE="app/build.gradle.kts"
        VERSION_CODE=$(grep "versionCode" $GRADLE_FILE | awk -F'=' '{print $2}' | tr -d -c '0-9')
        CURRENT_VERSION_NAME=$(grep "versionName =" $GRADLE_FILE | awk -F'=' '{print $2}' | tr -d -c '0-9.')
        
        IFS='.' read -r major minor patch <<< "$CURRENT_VERSION_NAME"
        
        case ${{ inputs.bump-type }} in
          major)
            major=$((major + 1))
            minor=0
            patch=0
            ;;
          minor)
            minor=$((minor + 1))
            patch=0
            ;;
          patch)
            patch=$((patch + 1))
            ;;
        esac
        
        echo "NEW_VERSION_CODE=$((VERSION_CODE + 1))" >> $GITHUB_ENV
        echo "NEW_VERSION_NAME="$major.$minor.$patch"" >> $GITHUB_ENV
      shell: bash

    - name: Edit build.gradle
      run: |
        GRADLE_FILE="app/build.gradle.kts"
        sed -i "s/versionCode = .*/versionCode = $NEW_VERSION_CODE/" $GRADLE_FILE
        sed -i "s/versionName = \".*\"/versionName = \"$NEW_VERSION_NAME\"/" $GRADLE_FILE
      shell: bash
