name: Bump version

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump version
        run: |
          VERSION_FILE="app/build.gradle.kts"
          VERSION_CODE=$(grep "versionCode" $VERSION_FILE | awk -F'=' '{print $2}' | tr -d -c '0-9')
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          TAG=${{ github.ref }}
          NEW_VERSION_NAME=${TAG//v}

          sed -i "s/versionCode = .*/versionCode = $NEW_VERSION_CODE/" $VERSION_FILE
          sed -i "s/versionName = \".*\"/versionName = \"NEW_VERSION_NAME\"/" $VERSION_FILE 

          echo "NEW_VERSION_CODE=$NEW_VERSION_CODE" >> $GITHUB_ENV
          echo "NEW_VERSION_NAME=$NEW_VERSION_NAME" >> $GITHUB_ENV

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit new version
        run: |
          TAG=${{ github.ref }}
          git commit -a -m "Versao ${{ github.ref }}"
          git tag -f -a $TAG -m "$TAG"
          git log --oneline
          git push origin
          git push origin $TAG