name: Create new release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: new app version
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Run unit tests
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: ./gradlew clean app:testProductionDebugUnitTest

      - name: Bump app version
        uses: ./.github/actions/android-version-bump
        with:
          version: ${{ inputs.tag }}

      - name: Build Android App Bundle
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: ./gradlew app:assembleRelease

      - name: Create release
        run: gh release create ${{ inputs.tag }} --title=${{ inputs.tag }} --generate-notes

      - name: Upload release assets
        run: |
          gh release upload ${{ inputs.tag }} \
            app/build/outputs/apk/production/release/app-production-release.apk \
            app/build/outputs/apk/staging/release/app-staging-release.apk
