name: Create new release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: new app version
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Check version
        run: |
          TAG=${{ inputs.tag }}
          VERSION_NAME=$(grep "versionName =" app/build.gradle.kts | awk -F'=' '{print $2}' | tr -d -c '0-9.')

          if [ "$(printf '%s\n' "${TAG//v}" "$VERSION_NAME" | sort -V | head -n1)" = "${TAG//v}" ]; then 
              echo "Fail: new version ($TAG) is less than or equal to the current version ($VERSION_NAME)."
              exit 1
          fi

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Run unit tests
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: ./gradlew clean app:testProductionDebugUnitTest

      - name: Bump app version
        uses: ./.github/actions/android-version-bump
        with:
          version: ${{ inputs.tag }}

      - name: Build Android App Bundle
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: ./gradlew app:assembleRelease

      - name: Create release
        run: gh release create ${{ inputs.tag }} --title=${{ inputs.tag }} --generate-notes

      - name: Upload release assets
        run: |
          gh release upload ${{ inputs.tag }} \
            app/build/outputs/apk/production/release/app-production-release.apk \
            app/build/outputs/apk/staging/release/app-staging-release.apk
