name: Create new release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: new app version
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Bump app version
        uses: ./.github/actions/android-version-bump
        with:
          version: ${{ inputs.tag }}

      - name: Create release
        run: gh release create ${{ inputs.tag }} --title=${{ inputs.tag }} --generate-notes
