name: Pull Request - Build APK

on:
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'Status - Ready 4 test' }}
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Build APK - STG
        env:
          VERSION_SUFFIX: ${{ format('PR{0}', github.event.pull_request.number) }}
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: ./gradlew clean app:assembleStagingRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-staging-release
          path: app/build/outputs/apk/staging/release/app-staging-release.apk

  deploy-firebase:
    runs-on: ubuntu-latest
    needs: build
    env:
      GOOGLE_APPLICATION_CREDENTIALS: firebase_credentials.json
      FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-staging-release

      - name: Setup firebase CLI
        run: |
          echo $FIREBASE_CREDENTIALS > $GOOGLE_APPLICATION_CREDENTIALS
          if ! [ -x "$(command -v firebase)" ]; then
            curl -sL https://firebase.tools | bash
          fi

      - name: Upload to firebase app distribution
        run: |
          firebase appdistribution:distribute app-staging-release.apk \
            --app ${{ vars.FIREBASE_APP_ID }} \
            --groups "dev, qa"
