name: Pull Request - Build APK

on:
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'Status - Ready 4 test' }}
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Build APK - STG
        env:
          VERSION_SUFFIX: ${{ format('PR{0}', github.event.pull_request.number) }}
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: ./gradlew clean app:assembleStagingDebug

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-staging-debug
          path: app/build/outputs/apk/staging/debug/app-staging-debug.apk

  deploy-firebase:
    runs-on: ubuntu-latest
    needs: build
    env: 
      GOOGLE_APPLICATION_CREDENTIALS: firebase_credential.json

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-staging-debug

      - name: Setup firebase credentials
        run: ${{ secrets.FIREBASE_CREDENTIALS }} > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Install firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Upload to firebase app distribution
        run: |
          firebase appdistribution:distribute app-staging-debug.apk \
            --app ${FIREBASE_APP_ID} \
            --groups "dev, qa"
