name: Pull Request - Tests

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Run lint checks and unit tests
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: ./gradlew clean app:lintStagingDebug app:testStagingDebugUnitTest

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/tests/testStagingDebugUnitTest
            app/build/reports/lint-results-stagingDebug.*
