name: Pull Request - Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Run lint check and unit tests
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: |
          chmod +x gradlew
          ./gradlew clean app:lintStagingDebug app:testStagingDebugUnitTest

      - name: Upload reports
        if: always()
        continue-on-error: true # for local tests
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/tests/testStagingDebugUnitTest
            app/build/reports/lint-results-stagingDebug.*
