name: Pull Request - Tests - Image android-env

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jeff-soares/android-env:latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install fastlane
        run: bundle install

      - name: Run unit tests
        run: bundle exec fastlane test

      - name: Upload reports
        if: ${{ always() && !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: app/build/reports/tests/testStagingDebugUnitTest
