name: Pull Request - Tests

on:
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: codebuild-workflow-${{ github.run_id }}-${{ github.run_attempt }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Run tests
        run: ./gradlew app:testStagingDebugUnitTest -Ptest --no-daemon

      - name: Upload reports
        if: always() && !env.ACT
        uses: actions/upload-artifact@v6
        with:
          name: test-reports
          path: app/build/reports/tests/testStagingDebugUnitTest
