name: Publish app to GooglePlay

on:
  release:
    types: [released]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version
        run: |
          TAG=$(gh release view --json tagName --jq '.tagName')
          VERSION_NAME=$(grep "versionName =" app/build.gradle.kts | awk -F'=' '{print $2}' | tr -d -c '0-9.')

          if [ "${TAG//v}" != "$VERSION_NAME" ]; then
              echo "Fail: app versionName ($VERSION_NAME) and release tag ($TAG) are different"
              exit 1
          fi

      - name: Download release app bundle
        uses: gh release download --pattern app-production-release.aab

      - name: Create service account file
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
        run: echo "$GOOGLE_PLAY_SERVICE_ACCOUNT" > service_account.json

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install fastlane
        run: bundle install

      - name: Build and publish to closed test track
        run: bundle exec fastlane deploy
