name: Release - Create release pull request

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: type of bump
        type: choice
        options:
          - major
          - minor
          - patch
        default: patch
      release-type:
        description: type of release
        type: choice
        options:
          - release
          - prerelease
        default: release

env:
  GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Bump app version
        uses: ./.github/actions/android-version-bump
        with:
          bump-type: ${{ inputs.bump-type }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: Commit new version
        run: |
          RELEASE_BRANCH="${{ inputs.release-type }}/$NEW_VERSION_NAME"
          git checkout -b "$RELEASE_BRANCH"
          git add app/build.gradle.kts
          git commit -m "Versao v$NEW_VERSION_NAME"
          git push origin "$RELEASE_BRANCH"
        shell: bash

      - name: Generate release notes
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "## What's Changed
          $(git log $LAST_TAG... --pretty=format:"- %s (%h)" --grep="Merge pull request")
          " >> release-notes.md

      - name: Create release PR
        run: |
          gh pr create --base master \
            --head "${{ inputs.release-type }}/$NEW_VERSION_NAME" \
            --title "${{ inputs.release-type }}: v$NEW_VERSION_NAME" \
            --body "$(cat release-notes.md)"
