name: Release - Publish app to GooglePlay

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  pull-requests: read

env:
  KEYSTORE: ${{ secrets.KEYSTORE }}
  GOOGLE_PLAY_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}

jobs:
  publish:
    runs-on: codebuild-workflow-${{ github.run_id }}-${{ github.run_attempt }}
    container:
      image: ruby:3.4.5-bookworm
    timeout-minutes: 30

    steps:
      - name: Set up Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Install fastlane
        run: bundle install

      - name: Build Release
        run: bundle exec fastlane build_release

      - name: Publish to Google Play
        run: bundle exec fastlane publish_google_play

      - name: Upload to Github Release Assets
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836
        with:
          files: |
            app/build/outputs/bundle/productionRelease/app-production-release.aab

  build-apk:
    runs-on: codebuild-workflow-${{ github.run_id }}-${{ github.run_attempt }}
    timeout-minutes: 30

    steps:
      - name: Set up Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Build APK
        run: ./gradlew app:assembleProductionRelease

      - name: Upload to Github Release Assets
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836
        with:
          files: |
            app/build/outputs/apk/production/release/app-production-release.apk
