name: Fastlane - Unit Tests

on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Run unit tests with fastlane
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: bundle exec fastlane test
