name: Release - Publish app to GooglePlay

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  pull-requests: read

env:
  KEYSTORE: ${{ secrets.KEYSTORE }}
  GOOGLE_PLAY_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jeff-soares/android-env:latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Install fastlane
        run: bundle install

      - name: Send Release Notification
        run: |
          bundle exec fastlane send_release_notification \
            version_name:"${{ github.ref_name }}" \
            webhook_url:"${{ secrets.WEBHOOK_URL }}" \
            gh_token:"${{ secrets.GITHUB_TOKEN }}"
